postgis:
  image: kartoza/postgis:9.4-2.1
  hostname: postgis
  ports:
  - "5432:5432"
  volumes:
  - ./postgis:/tmp/postgis
geoserver:
  build: geoserver 
  hostname: geoserver
  ports:
  - "8080:8080"
  links:
  - postgis:postgis
  volumes:
  - ./geoserver_data:/srv/geoserver
  - ./geoserver:/tmp/geoserver
preview:
  build: preview 
  hostname: preview
  ports:
  - "80:80"
  links:
  - geoserver:geoserver
